name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker sync tool image
      run: docker build . --target sync --file Dockerfile --tag jaroslawhartman/withings_sync:$(date +%s)
  build-sync-cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker cron job image
      run: docker build . --target sync-cron --file Dockerfile --tag jaroslawhartman/withings_sync_cron:$(date +%s)
